server:
  port: 8036
  compression:
    enabled: true
spring:
  application:
    name: cr
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mariadb://172.16.131.11:3306/
#    username: tes_admin
#    password: tjdrhd@ro
    username: root
    password: '!@his08'
    driver-class-name: org.mariadb.jdbc.Driver
  messages:
    basename: i18n/common/messages
    encoding: UTF-8
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
Klago:
  mode: live
  dbType: mariadb
  event:
    url: http://172.16.121.40:80
  Sign:
    Value: 4edec53cebbe603e34458532505c45
  groupware:
    domain: http://dev.bizcubex.co.kr
  redis:
    ip: 14.41.2.189
    port: 16384
    password: 1234
  sms:
    # 운영
    #server: http://bizcubex.cloudfax.co.kr

    # 개발
    #server: http://172.16.112.85:9013

    # 로컬
    server: http://172.16.112.85:9014

logging:
  config: ./log4j2.xml


management:
  endpoint:
    health:
      show-details: always